### ISSUE TITLE
Error launching application on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by alexpreston** [abuanwar072/Course-App#2]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           13.9s
Failed to build iOS app
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
../../Desktop/workspace/flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^

**Comment by abuanwar072** [comment]
Problem fixed, please clone it again.
